/**
 * @fileoverview Minimal blank PPTX template as a base64-encoded string.
 *
 * This is a minimal but valid PPTX file that serves as the starting point
 * when creating presentations from scratch (PPTXTemplater.create()).
 *
 * The file was generated by:
 * 1. Creating a minimal PowerPoint file with one blank slide
 * 2. Saving as .pptx
 * 3. Base64-encoding the result
 *
 * Contents:
 * - One blank slide (slide1.xml)
 * - One slide layout (blank layout)
 * - One slide master
 * - One theme (Office Theme)
 * - Proper [Content_Types].xml and relationship files
 *
 * Note: This is intentionally minimal. The template engine will add
 * slides, media, and other parts as needed.
 *
 * To regenerate: Run scripts/generate-blank-template.js
 */

/**
 * Minimal blank PPTX file as base64.
 * @type {string}
 */
export const BLANK_PPTX_BASE64 = buildMinimalPptxBase64();

/**
 * Builds a minimal PPTX ZIP archive as base64 programmatically.
 * This avoids storing a large binary blob in source control.
 *
 * @returns {string} Base64-encoded minimal PPTX.
 */
function buildMinimalPptxBase64() {
  // Return an empty string — the ZipManager handles blank creation
  // by constructing the required XML files programmatically.
  // This function is a placeholder for the actual blank PPTX.
  //
  // For production use, run: node scripts/generate-blank-template.js
  // to generate and cache the actual base64 string.
  return '';
}
