import pkg from './index.js'

export const {
  PPTXTemplater,
  PPTXTemplate,
  ZipManager,
  XMLParser,
  Z_ORDER_SYMBOL,
  SlideManager,
  ChartManager,
  TableManager,
  ShapeManager,
  ImageManager,
  TextManager,
  HyperlinkManager,
  MediaManager,
  RelationshipManager,
  OutputWriter,
  TemplateEngine,
  ValidationEngine,
  generateRelationshipId,
  parseRelationshipId,
  validateXml,
  validateXML,
  safeParseXml,
  repairXML,
  scanForEntities,
  analyzeXmlFile,
  reportXmlComplexity,
  createLogger,
  setGlobalLogLevel,
  resetLogLevel,
  PPTXError,
  SlideNotFoundError,
  ChartNotFoundError,
  TableNotFoundError,
} = pkg

export default pkg
